# sudo: required # for wine
language: node_js
node_js:
- 6
- 5

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
  - master
  - "/^v?[0-9](\\.[0-9])*/"

before_script:
  # - sudo apt-get -y -qq install wine # for win32 app build
  # - export DISPLAY=:99.0
  # - sh -e /etc/init.d/xvfb start
  - npm run build

script:
  - ls build

after_success:
- curl https://raw.githubusercontent.com/KamataRyo/travis-sctipts-collection/master/deploy-electron-apps.sh | bash

env:
  global:
  - NODE_VERSION_TO_DEPLOY: 5
  - GH_REF: github.com:wakayamarb/1min-timer.git
  - secure: "5yaNXnxBl9h4hDQLLBksN3QyswPWVGfh2Kz0jGsyNw4Wz7sJXG+63948txBQ9dhedDPl8BBPsvckOshjS6OS5ZcKIDKEuc1L+dfnut0hhZN2B99PvtfI51Duyn2rpaP148/MjLTAhacQtv25SovIai4tJuqHpjIVwk81frzndvoCVY31b+XszIswGN6QzBS0L+BjCUCBVp7OQu8byweizFLbJAzwY3MagoAkE4h3fvAxQn91nbHUJtvqahYHPi+JpMfeHHVGSnec9auSui0E/XNA/oP2DQwFE0Q/uAJcTEdluPauUhhiEr5AQ8fDPuTn3vC9jLlavbXJ4PS6ipyxtHmYSXjpdLOYyl0VJ+cxF8OYvUp3gbzIYczOd+uEyh1PENhiSs1fE+pFSJU9vSsOsf86ldaLx7TCRLHy/xHiqSt81KRjIaUKgr1HndSUKXQB4ouC6EAm4svxTyOE0K4Q2P5hHGlGpohFJG58AvMsT13j5Ag69Bz9RiLxkwqe3iZsYpezbShef06IkHvl0Sf/jVipG6QvhVaaFwjvm4OatiSrMENa2dSvmOYWXyRJaLAYOmTOPHsS3FFPvpiOrkWFUBDYoasKLnQYRDHZRshXef5b6GYqp7j3DvyJob5GAdfyJSbICTCUfah7RalI5HaoZGsC8MvFD4lmezLoLsSTLFs="
